Added migration to limit varchars in database.
KEA-RPG/Thread-of-nine-lives pull request #50
Opened 2024-12-06 18:31 UTC by Troels-dat21B

Added debugging for Relational Migrator

2024-12-09 08:01 UTC, Bjand49 approved these changes

2024-12-09 08:06 UTC, Bjand49 requested changes
Der mangler at blive kørt noget migration data på i migrations, den burde blive fjernet og kørt på igen

2024-12-10 11:05 UTC, Bjand49 commented on Infrastructure/Persistance/Relational/Configurations/CommentConfiguration.cs
> +            builder.Property(c => c.Text).HasColumnType("nvarchar(350)");
builder.Property(c => c.Text).HasMaxLength(350).HasColumnType("nvarchar(350)");

2024-12-10 11:05 UTC, Bjand49 approved these changes

2024-12-10 17:09 UTC, Troels-dat21B commented on Infrastructure/Persistance/Relational/Configurations/CommentConfiguration.cs
> +            builder.Property(c => c.Text).HasColumnType("nvarchar(350)");
Dette blev implementeret kort efter det blev nævnt

2024-12-11 17:44 UTC, Bjand49 approved these changes

2024-12-12 21:22 UTC, merged